### ISSUE TITLE
NPM Install does not working

### ISSUE THREAD

**Issue by kratewong** [tangtan/iStoryline.js#23]
Hi Tangtan,

I was trying to implement your web app in my research project. 

But I found some errors when installing it on my machine. Please check the installation log below.

npm ERR! code ECONNREFUSED
npm ERR! syscall connect
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://npm.zjvis.org/xmlbuilder/-/xmlbuilder-11.0.1.tgz failed, reason: connect ECONNREFUSED 10.5.24.47:443
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:110:14)
npm ERR!     at ClientRequest.emit (node:events:390:28)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:447:9)
npm ERR!     at TLSSocket.emit (node:events:402:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR!  FetchError: request to https://npm.zjvis.org/xmlbuilder/-/xmlbuilder-11.0.1.tgz failed, reason: connect ECONNREFUSED 10.5.24.47:443
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:110:14)
npm ERR!     at ClientRequest.emit (node:events:390:28)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:447:9)
npm ERR!     at TLSSocket.emit (node:events:402:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '10.5.24.47',
npm ERR!   port: 443,
npm ERR!   type: 'system'
npm ERR! }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

I am looking forward to hearing from you.

Best

**Comment by tangtan** [comment]
Hi, I notice there are some network connection errors due to the existence of xmlbuilder. I have fixed this issue by updating package-lock.json but I am afraid the npm registry cannot reflect this update immediately. So, I suggest

1. delete package-lock.json in your cloned repo and run npm install again.
2. download this project from github directly and do not use npm install i-istoryline-js.
