### ISSUE TITLE
Where can I find the Web UI presented in your material?

### ISSUE THREAD

**Issue by tiange997** [tangtan/iStoryline.js#24]
Tangtan大佬你好

我现在的版本只可以手动coding来变换颜色自定义线条啥的，和你paper里展示的东西有点差别。

想请问一下paper里的这个带UI的系统是开源的吗？如果是哪里可以下载到？

如果不是开源的话 想了解一下怎么在这些线条前面加上角色的名字？

方便的话能否留个联系方式wx啥的？

非常感谢！

**Comment by tangtan** [comment]
The paper version is implemented in C# and uploaded to our group repo. Plz check this link: https://github.com/zjuidg/iStoryline.
